version: '3'

services:
  quill:
    image: nginx:alpine
    volumes:
      - .deploy/quill.conf:/etc/nginx/conf.d/default.conf
      - static:/srv/playground/.static
    networks:
      - default
      - proxy

  django:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - static:/srv/playground/.static
    command: sh -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn.py config.wsgi'
    networks:
      - default

volumes:
  static:

networks:
  default:
  proxy:
    external: true
